### ISSUE TITLE
Strided OctConv probably wrong

### ISSUE THREAD

**Issue by andravin** [ThoroughImages/OctConv#1]
https://github.com/ThoroughImages/OctConv/blob/6d4c6b4bff32d580248811e58cdd71e348fa9dd2/octconv.py#L72

The emerging consensus is that this is the wrong way to implement strided convolutions in OctConv. See https://github.com/terrychenism/OctaveConv/issues/4

**Comment by savourylie** [comment]
https://github.com/ThoroughImages/OctConv/blob/6d4c6b4bff32d580248811e58cdd71e348fa9dd2/octconv.py#L72-L74

I believe you're referring to this part of the code.

I've gone through the thread and I'm not sure I share your concern. Correct me if I'm wrong but according to this part of the paper:

> However, since the index of X_H can only be an integer, we could either round the index to (2∗p+i, 2∗q+j) or approximate the value at (2∗p+0.5+i, 2∗q+0.5+j) by averaging all 4 adjacent locations. The first one is also known as strided convolution and the second one as average pooling. As we discuss in Section 3.3 and Fig. 3, strided convolution leads to misalignment; we therefore use average pooling to approximate this value for the rest of the paper.

Average pooling is chosen due to that strided convolutions may lead to misalignment. This is how it is implemented in most of the repos you listed I believe.

**Comment by andravin** [comment]
I am actually referring to the `self.stride` parameter, and the case when it is not equal to 1.

**Comment by savourylie** [comment]
> I am actually referring to the `self.stride` parameter, and the case when it is not equal to 1.

I see your point. Yes, the authors didn't make it clear in the paper how strided convolutions are handled in the context. My understanding is that the paper assumed that the stride is always 1 so that this operation can easily be adopted to group / depthwise convolutions. As to how it would handle strided convolutions...I'm with other implementations that we could use average pooling for the same reason why it is used in the case of downsampling/upsampling.

**Comment by andravin** [comment]
Yes, seems likely the authors did some version of that, exactly what I do not know.

**Comment by savourylie** [comment]
Cool. I'm closing this issue as this seems to go a bit open-ended. Thanks for letting me know as I didn't really think about this.

**Comment by andravin** [comment]
The authors' reference implementation is out now: https://github.com/facebookresearch/OctConv
